<!DOCTYPE html>
<html lang="en">
<head>
    <!--Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--Libraries used by Bootstrap-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>

    <!--Font awesome CSS-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!--Bootstrap JS-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    <!--Custom css-->
    <link rel="stylesheet" href="css/custom-css.css">

    <title>Admin - Users listing</title>
</head>

<body>
<!--Header-->
<div class="d-flex flex-column flex-md-row align-items-center p-3 mb-3 bg-light border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal">Quiz</h5>
    <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark">Hello!</span>
    </nav>
    <a class="btn btn-secondary" href="/logout">Logout</a>
</div>

<!--Breadcrumbs-->
<nav aria-label="breadcrumb">
    <ol class="breadcrumb px-3 py-0 mb-3">
        <li class="breadcrumb-item"><a href="/dashboard">Dashboard</a></li>
        <li class="breadcrumb-item active" aria-current="page">Users listing</li>
    </ol>
</nav>

<div class="container">
    <!--Page title block-->
    <div class="text-center">
        <h1>Users listing</h1>
    </div>

    <!--Table actions block-->
    <div class="row">
        <div class="col-12 col-md-6">
            <form class="form-inline" action="/dashboard/users" method="POST">
                <div class="form-group">
                    <label for="roleSearch"></label>
                    <select name="role" class="form-control" id="roleSearch">
                        <?php foreach ($users as $user): ?>
                        <option value="<?php echo $user->getRole() ?>"><?php echo $user->getRole() ?></option>
                        <?php endforeach;?>
                    </select>
                </div>
                <button type="submit" class="btn btn-primary">Search</button>
            </form>

        </div>
        <div class="col-12 col-md-6 d-flex align-items-end justify-content-end">
            <a class="btn btn-primary py-1 mb-3" href="/dashboard/users/add">Add new user</a>
        </div>
    </div>


    <!--Quiz listing table-->
    <div class="table-responsive my-4">
        <table class="table table-bordered">
            <thead>
            <tr>
                <!--Sorting arrow are displayed using the 'asc','dsc' classes-->
                <th scope="col" class="sorting-header asc dsc">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Role</th>
                <th scope="col">Actions</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($users as $user): ?>
                 <tr>
                    <th scope="row"><?php echo $user->getId()?></th>
                    <td><?php echo $user->getName()?></td>
                    <td><?php echo $user->getRole()?></td>
                    <td class="text-center">
                        <a class="btn btn-primary py-1" href="/dashboard/users/update/<?php echo $user->getId() ?>">Edit</a>
                        <a class="btn btn-danger py-1" href="/dashboard/users/delete/<?php echo $user->getId() ?>">Delete</a>
                    </td>
                </tr>
            <?php endforeach;?>

            </tbody>
        </table>
    </div>

    <!--Pagination block-->
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            <li class="page-item">
                <?php
                $page = $paginator->getCurrentPage();

                $totalPages= $paginator->getTotalPages()
                ?>
                <a class="page-link" href="?page=<?php echo ($page < 2) ? $page : $page-1 ?>">Previous</a>
            </li>
            <?php for ($i = 0; $i < $totalPages; $i++) : ?>
            <li class="page-item"><a class="page-link" href="?page=<?php echo $i+1?>"><?php echo $i+1 ?></a></li>
            <?php endfor;?>
            <li class="page-item">
                <a class="page-link" href="?page=<?php echo ($page < $totalPages)? $page + 1 : $page ?>">Next</a>
            </li>
        </ul>
    </nav>
</div>
</body>
</html>