<!DOCTYPE html>
<html lang="en">
<head>
    <!--Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!--Libraries used by Bootstrap-->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

    <!--Font awesome CSS-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">

    <!--Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!--Bootstrap JS-->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <!--Custom css-->
    <link rel="stylesheet" href="css/custom-css.css">

    <title>Admin - User details</title>
</head>

<body>
    <!--Header-->
    <div class="d-flex flex-column flex-md-row align-items-center p-3 mb-3 bg-light border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal">Quiz</h5>
        <nav class="my-2 my-md-0 mr-md-3">
            <span class="p-2 text-dark">Hello!</span>
        </nav>
        <a class="btn btn-danger" href="/logout">Logout</a>
    </div>

    <!--Breadcrumbs-->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb px-3 py-0 mb-3">
            <li class="breadcrumb-item" ><a href="/dashboard">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">User details</li>
        </ol>
    </nav>

    <div class="container">
        <!--Page title block-->
        <div class="text-center">
            <h1>New user / Edit user</h1>
        </div>

        <?php if($user !== ""): ?>
        <!--User details form-->
        <form method="POST">
            <div class="form-group">
                <label for="userName">Name</label>
                <input type="text" name="name" value="<?php echo $user->getName() ?>" class="form-control" id="userName" placeholder="<?php echo $user->getName() ?>">
            </div>
<!--            <div class="form-group">-->
<!--                <label for="userEmail">Email</label>-->
<!--                <input type="email" name="email" class="form-control" id="userEmail" placeholder="User email">-->
<!--            </div>-->
            <div class="form-group">
                <label for="userPassword">Password</label>
                <input type="password" name="password" class="form-control" id="userPassword" placeholder="User password">
            </div>
            <div class="form-group">
                <label for="userRole">Role</label>
                <select name="role" class="form-control" id="userRole">
                    <option value="admin">admin</option>
                    <option value="user">user</option>
                </select>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>
            <?php else: ?>
        <!--User details form-->
        <form method="POST">
                <div class="form-group">
                    <label for="userName">Name</label>
                    <input type="text" name="name" class="form-control" id="userName" placeholder="name">
                </div>
<!--                <div class="form-group">-->
<!--                    <label for="userEmail">Email</label>-->
<!--                    <input type="email" name="email" class="form-control" id="userEmail" placeholder="User email">-->
<!--                </div>-->
                <div class="form-group">
                    <label for="userPassword">Password</label>
                    <input type="password" name="password" class="form-control" id="userPassword" placeholder="User password">
                </div>
                <div class="form-group">
                    <label for="userRole">Role</label>
                    <select name="role" class="form-control" id="userRole">
                        <option value="admin">admin</option>
                        <option value="user">user</option>
                    </select>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            <?php endif; ?>
        </form>
    </div>
</body>
</html>